const MaterialDispatchYewaleQuestions = {
  id: "material_dispatch_yewale_form",
  title_mr: "मटेरियल डिस्पॅचसाठी नियोजन येवले",
  title_en: "PLANNING FOR MATERIAL DISPATCH YEWALE",
  fields: [
    {
      id: "ss_counter_checking",
      question_mr: "एसएस काउंटर तपासणी",
      question_en: "SS Counter Checking",
      type: "table",
      subfields: [
        {
          id: "display_counter",
          label_mr: "डिस्प्ले काउंटर",
          label_en: "Display Counter",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "service_counter",
          label_mr: "सर्व्हिस काउंटर",
          label_en: "Service Counter",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "cash_counter",
          label_mr: "कॅश काउंटर",
          label_en: "Cash Counter",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "sink",
          label_mr: "सिंक",
          label_en: "Sink",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "two_burner_bhatti",
          label_mr: "२-बर्नर भट्टी",
          label_en: "2-Burner Bhatti",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "work_table",
          label_mr: "वर्क टेबल",
          label_en: "Work Table",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "cup_table",
          label_mr: "कप टेबल",
          label_en: "Cup Table",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
        {
          id: "ss_tray",
          label_mr: "एसएस ट्रे",
          label_en: "SS Tray",
          type: "radio",
          hasSide: false,
          hasWeight: true,
          hasRemark: true,
          required: true,
        },
      ],
    },
    {
      id: "housekeeping_material",
      question_mr: "हाउसकीपिंग मटेरियल",
      question_en: "Housekeeping Material",
      type: "status",
      subfields: [
        {
          id: "material",
          label_mr: "हाउसकीपिंग मटेरियल",
          label_en: "Housekeeping Material",
          type: "radio",
          required: true,
        },
      ],
    },
    {
      id: "transport_booking",
      question_mr: "ट्रान्सपोर्ट बुकिंग",
      question_en: "Transport Booking",
      type: "status",
      subfields: [
        {
          id: "booking",
          label_mr: "ट्रान्सपोर्ट बुकिंग",
          label_en: "Transport Booking",
          type: "radio",
          required: true,
        },
      ],
    },
    {
      id: "dispatch_date",
      question_mr: "डिस्पॅच तारीख",
      question_en: "Dispatch Date",
      type: "date",
      subfields: [
        {
          id: "date",
          label_mr: "तारीख",
          label_en: "Date",
          type: "date",
          required: true,
        },
      ],
    },
    {
      id: "material_dispatch",
      question_mr: "मटेरियल डिस्पॅच",
      question_en: "Material Dispatch",
      type: "status",
      subfields: [
        {
          id: "dispatch",
          label_mr: "मटेरियल डिस्पॅच",
          label_en: "Material Dispatch",
          type: "radio",
          required: true,
        },
      ],
    },
  ],
  submit_button_mr: "सबमिट करा",
  submit_button_en: "Submit",
  navigation_buttons: {
    back_mr: "मागे",
    back_en: "Back",
    next_mr: "पुढे",
    next_en: "Next",
  },
  submission_message_mr:
    "सर, आपले खूप खूप धन्यवाद की आपण वरील पूर्ण माहिती आम्हाला दिली आहे. आम्ही तुम्हाला मटेरियल डिस्पॅचसाठी लागणाऱ्या सर्व गोष्टींची माहिती पुढील कामाच्या वेळेत 24 तासाच्या आत मध्ये पाठवू आणि त्यानंतर तुम्हाला वास्तविक कामाबद्दल पूर्ण माहिती दिली जाईल. धन्यवाद.",
  submission_message_en:
    "Thank you very much sir for providing us with all the above information. We will send you all the details required for material dispatch within 24 hours of the next working time, and after that, you will be given complete information about the actual work. Thank you.",
};

export default MaterialDispatchYewaleQuestions;