const ChallangesPlan1Questions = {
  id: "challanges_plan1_form",
  title_mr: "चॅलेंजेस प्लॅन १ साठी नियोजन",
  title_en: "PLANNING FOR CHALLENGES PLAN 1",
  steps: [
    {
      id: "area_shop_size",
      title_mr: "क्षेत्र (दुकान आकार आणि स्टोर रूम)",
      title_en: "Area (Shop Size & Store Room)",
      challenges_mr: [
        "दुकान आकार (150–300 चौ.फूट) सेटअप आणि ऑपरेशन्समध्ये अडचणी निर्माण करतो.",
        "कच्च्या मालाची साठवणूक अपुरी आहे.",
        "बंद केल्यानंतर गोल टेबल्स ठेवण्यात अडचण येते.",
      ],
      challenges_en: [
        "Limited shop size (150–300 sq.ft.) creates issues in setup and operations.",
        "Insufficient raw material storage.",
        "Difficulty in placing round tables after closing.",
      ],
      mitigation_mr: [
        "किमान 300 चौ.फूट क्षेत्र स्टोर रूमसह प्रदान करा.",
        "लहान दुकानांसाठी बाहेरील समर्पित साठवणूक जागा व्यवस्थापित करा किंवा कॉम्पॅक्ट साठवणूक समाधान तयार करा.",
        "फर्निचर लेआउट ऑप्टिमाइझ करा जेणेकरून बंद केल्यानंतर साठवणूक लवचिकता सुनिश्चित होईल.",
      ],
      mitigation_en: [
        "Provide minimum 300 sq.ft. area including store room.",
        "For smaller shops, arrange dedicated storage space externally or create compact storage solutions.",
        "Optimize furniture layout to ensure post-closing storage flexibility.",
      ],
    },
    {
      id: "layout",
      title_mr: "लेआउट",
      title_en: "Layout",
      challenges_mr: [
        "थीम-आधारित लेआउट तयार केलेले आहे, परंतु मालकाकडून अखेरचे बदल वारंवार केले जातात.",
        "NB FIDM टीमच्या मंजुरीत विलंब होतो.",
      ],
      challenges_en: [
        "Theme-based layout prepared but final changes often made by owner.",
        "Delays in NB FIDM team approval.",
      ],
      mitigation_mr: [
        "मालकाच्या बाजूने एक अधिकृत व्यक्ती मंजुरीसाठी नियुक्त करा.",
        "अंमलबजावणीपूर्वी NB टीमकडून सोपी आणि थेट मंजुरी मिळवा.",
        "सर्व हितसंबंधींच्या सह्या घेऊन अंतिम लेआउट लॉक करा.",
      ],
      mitigation_en: [
        "Appoint one authorized person from the owner’s side for approvals.",
        "Obtain easy and direct approvals from NB team before execution.",
        "Ensure final layout is locked and signed off by all stakeholders.",
      ],
    },
    {
      id: "wall_tiles_work",
      title_mr: "वॉल टायल्स कार्य",
      title_en: "Wall Tiles Work",
      challenges_mr: [
        "आसन टायल्स नवीन थीमसह विसंगत आहेत.",
        "दुकान आकारातील बदल अंमलबजावणीस प्रभावित करतात.",
        "बजेट मर्यादा; मालक टायल्स बदलण्यास हिचकतात.",
        "मालक टायल्स बदलण्यास नकार देऊ शकतात.",
      ],
      challenges_en: [
        "Existing tiles conflict with new theme.",
        "Variation in shop sizes affects implementation.",
        "Budget constraints; owners hesitate to replace tiles.",
        "Owners may refuse to change tiles.",
      ],
      mitigation_mr: [
        "स्वीकारार्ह टायल्स पर्यायांबाबत स्पष्ट खुलासा द्या.",
        "कॉर्पेट क्षेत्राच्या आधारावर थीम लॉक करा.",
        "पर्यायी समाधान ऑफर करा (टायल क्लॅडिंग, पेंटिंग, आंशिक बदल).",
      ],
      mitigation_en: [
        "Provide clear clarification on acceptable tile options.",
        "Lock theme based on carpet area.",
        "Offer alternate solutions (tile cladding, painting, partial replacement).",
      ],
    },
    {
      id: "plumbing_electrical_work",
      title_mr: "प्लंबिंग आणि इलेक्ट्रिकल कार्य",
      title_en: "Plumbing & Electrical Work",
      challenges_mr: [
        "भिंतीची जाडी 6 इंचापेक्षा कमी आहे, ज्यामुळे लपलेले काम अडचणीत येते.",
        "सोसायटी, दुकान मालक आणि शेजाऱ्यांकडून परवानग्या आवश्यक आहेत.",
        "इअर्थिंग आवश्यकता वारंवार दुर्लक्षित केली जाते.",
      ],
      challenges_en: [
        "Wall thickness less than 6” creates issues for concealed work.",
        "Permissions required from society, shop owner, and neighbours.",
        "Earthing requirements often overlooked.",
      ],
      mitigation_mr: [
        "खरे काम सुरू होण्यापूर्वी परवानगी पत्रे मिळवा.",
        "आसन इअर्थिंग पुरेसे नसेल तर नवीन इअर्थिंग स्थापित करा.",
        "लपलेले पाइपिंग/वायरिंग शक्य नसल्यास, नीटनेटके फिनिशिंगसह उघडे काम करा.",
      ],
      mitigation_en: [
        "Obtain permission letters before actual work starts.",
        "Install new earthing if existing is not adequate.",
        "If concealed piping/wiring not possible, execute as open work with neat finishing.",
      ],
    },
    {
      id: "pop_ceiling_work",
      title_mr: "POP (फॉल्स सीलिंग) कार्य",
      title_en: "POP (False Ceiling) Work",
      challenges_mr: [
        "विविध योजना पर्याय (पार्टिशन POP / पूर्ण POP / नाही POP).",
        "सीलिंगवर टिन शेड आहे.",
        "दुकान उंची 9 फूटपेक्षा कमी आहे.",
      ],
      challenges_en: [
        "Different plan options (partition POP / full POP / no POP).",
        "Ceiling has tin shade.",
        "Shop height less than 9 ft.",
      ],
      mitigation_mr: [
        "POP आवश्यकतांबाबत स्पष्ट खुलासा द्या.",
        "दुकान उंची ≥10 फूट असल्यास टिन शेडखाली POP स्थापित करा.",
        "दुकान उंची <9 फूट असल्यास POP अंमलात आणला जाणार नाही.",
      ],
      mitigation_en: [
        "Provide clear clarification on POP requirements.",
        "POP to be installed below tin shade if shop height ≥10 ft.",
        "If shop height <9 ft, POP will not be executed.",
      ],
    },
    {
      id: "ducting_exhaust",
      title_mr: "डक्टिंग / एक्झॉस्ट",
      title_en: "Ducting / Exhaust",
      challenges_mr: [
        "बजेट मर्यादा.",
        "एक्झॉस्ट बिंदू स्थान समस्या.",
        "परवानगी आव्हाने.",
        "थीम डिझाइनसह संरेखण.",
        "दुकान उंची मर्यादा.",
        "डक्ट आकार आणि क्षमता आवश्यकता.",
      ],
      challenges_en: [
        "Budget limitations.",
        "Exhaust point location issues.",
        "Permission challenges.",
        "Alignment with theme design.",
        "Shop height constraints.",
        "Duct size and capacity requirements.",
      ],
      mitigation_mr: [
        "खर्च कमी करण्यासाठी एक्झॉस्ट फॅन्सवर प्राधान्य द्या.",
        "एक्झॉस्ट बिंदू उपलब्ध नसल्यास डक्टिंग शटरपर्यंत विस्तारित करा.",
        "अंमलबजावणीपूर्वी मालकाला अंतिम योजनेची माहिती द्या.",
        "दुकान उंची <8 फूट आणि परवानगी नसल्यास, पार्टिशन भिंतीवर एक्झॉस्ट फॅन स्थापित करा.",
        "किमान आकार 15 इंच, कमाल 18 इंच असलेले एक्झॉस्ट फॅन्स वापरा.",
      ],
      mitigation_en: [
        "Prefer exhaust fans over ducting to reduce cost.",
        "If no exhaust points available, extend ducting up to shutter.",
        "Inform owner of final plan before execution.",
        "If shop height <8 ft and permission not available, install exhaust fan on partition wall.",
        "Use exhaust fans with minimum size 15”, maximum 18”.",
      ],
    },
    {
      id: "board_signage_work",
      title_mr: "बोर्ड / साइनेज कार्य",
      title_en: "Board / Signage Work",
      challenges_mr: [
        "मालक, सोसायटी, कॉर्पोरेशन, शेजारी यांच्याकडून अनेक परवानग्या आवश्यक आहेत.",
        "बोर्ड उंची आणि लांबीवर मर्यादा आहेत.",
        "अंमलबजावणी थीमसह संरेखित होऊ शकत नाही.",
      ],
      challenges_en: [
        "Multiple permissions required (owner, society, corporation, neighbours).",
        "Restrictions on board height and length.",
        "Execution may not align with theme.",
      ],
      mitigation_mr: [
        "फ्रँचाईझी मालकाने काम सुरू होण्यापूर्वी सर्व परवानग्या मिळवाव्यात.",
        "आकार मर्यादा असल्यास, 2–3 पर्यायी साइनेज डिझाइन्स तयार करा.",
        "थीम अंमलबजावणीच्या समस्यांमध्ये, अधिकृत डिझाइन/मंजूरी प्राधिकरणाकडे वाढवा.",
      ],
      mitigation_en: [
        "Franchise owner to secure all permissions before work begins.",
        "If size restrictions exist, prepare 2–3 alternate signage designs.",
        "In case of theme execution issues, escalate to authorized design/approval authority.",
      ],
    },
    {
      id: "gas_pipeline_work",
      title_mr: "गॅस पाइपलाइन कार्य",
      title_en: "Gas Pipeline Work",
      challenges_mr: [
        "पार्टिशन कामानंतर गॅस दाब कमी होतो कारण पाइपलाइन रस्ते लांब आहेत.",
        "दुकानात अनेक खांब → अतिरिक्त वाकणे (Elbows) लागतात, ज्यामुळे दाबात आणखी घट होते.",
        "मर्यादित दुकान क्षेत्र → गॅस बँक / गॅस बुकसाठी पुरेशी जागा नाही.",
        "गॅस गळतीचे धोके → चुकीची स्थापना किंवा साहित्य मॅचिंग.",
        "साहित्य उपलब्धता समस्या → MS / GI पाइप साइटवर उपलब्ध नाही; मालक तांबे पाइप्स वापरतो.",
      ],
      challenges_en: [
        "Low Gas Pressure after partition work due to longer pipeline routes.",
        "Multiple Columns in shop → requires additional bends (Elbows), causing further pressure drop.",
        "Limited shop area → insufficient space for proper gas bank / gas book placement.",
        "Gas Leakage Risks → improper installation or material mismatch.",
        "Material Availability Issues → MS / GI pipe not available on site; owner uses copper pipes instead.",
      ],
      mitigation_mr: [
        "पार्टिशन कामानंतर दाब चाचणी करा.",
        "किमान वाकणे/Elbows वापरा; पाइपलाइन लांबी कमी करण्यासाठी लेआउट ऑप्टिमाइझ करा.",
        "जिथे दाब कमी होण्याची शक्यता आहे तिथे मोठ्या व्यासाचे पाइप्स वापरा.",
        "पार्टिशन कामानंतर पाइपलाइन मार्ग नियोजित करा.",
        "गळती/दाब कमी होण्यापासून टाळण्यासाठी उच्च-गुणवत्तेचे elbows आणि फिटिंग्स वापरा.",
        "पर्यायी सुरक्षित ठिकाणे ओळखा (मागील सेटबॅक, छत, किंवा मंजूर मर्यादेत बाहेरील स्टोर).",
        "लहान जागेसाठी डिझाइन केलेले कॉम्पॅक्ट गॅस मॅनिफोल्ड सिस्टम्स वापरा.",
        "कमीशनिंगपूर्वी अनिवार्य दाब चाचणी करा.",
        "सर्व जोडण्या मंजूर साहित्याने सील करा.",
        "पाइपलाइन्ससाठी नियमित देखभाल आणि तपासणी वेळापत्रक ठेवा.",
        "सुरक्षितता मानकांनुसार फक्त मंजूर साहित्य (MS/GI पाइप्स) वापरा.",
        "तांबे पाइपिंग फक्त तात्पुरत्या जोडणीसाठी परवानगी आहे आणि ISI सुरक्षा नियमांचे पालन करावे.",
        "शाखा मालकाने गॅस लाइन कामासाठी प्रमाणित विक्रेता सुनिश्चित करावा.",
      ],
      mitigation_en: [
        "Conduct pressure testing after partition work.",
        "Use minimum bends/elbows; optimize layout to reduce pipeline length.",
        "Use larger diameter pipes where pressure drop is expected.",
        "Plan pipeline route during layout finalization.",
        "Use high-quality elbows and fittings to minimize leakage/pressure loss.",
        "Identify alternate safe locations (rear setback, rooftop, or outside store within approved limits).",
        "Use compact gas manifold systems designed for smaller spaces.",
        "Mandatory pressure test before commissioning.",
        "Ensure all joints are sealed with approved material.",
        "Regular maintenance & inspection schedule for pipelines.",
        "Use only approved material (MS/GI pipes) as per safety standards.",
        "Copper piping permitted only for temporary connections and must follow ISI safety norms.",
        "Branch owner to ensure certified vendor executes gas line work.",
      ],
    },
    {
      id: "cctv_camera",
      title_mr: "CCTV कॅमेरा",
      title_en: "CCTV Camera",
      challenges_mr: [
        "शाखा मालक खर्च कमी करण्यासाठी कमी गुणवत्तेचे कॅमेरे बसवतात.",
        "नॉन-ब्रँडेड कॅमेरे व्हिडिओ स्पष्टता, साठवणूक आणि सुरक्षा अनुपालनावर तडजोड करतात.",
        "कमी खर्चाच्या सिस्टमची आयुष्यमर्यादा कमी आणि देखभाल समस्या जास्त असतात.",
      ],
      challenges_en: [
        "Branch owners often install low-quality cameras to reduce cost.",
        "Non-branded cameras compromise on video clarity, storage, and security compliance.",
        "Low-cost systems have shorter lifespan and higher maintenance issues.",
      ],
      mitigation_mr: [
        "सर्व आउटलेट्सवर CCTV ब्रँड मानकीकरण करा → फक्त CP Plus कॅमेरे वापरा.",
        "शाखा मालकांना ब्रँड अनुपालन मंजुरीसाठी बंधनकारक असल्याचे स्पष्टपणे कळवा.",
        "सिव्हिल वर्क चेकलिस्टमध्ये CCTV तपशील (रिझोल्यूशन, साठवणूक, DVR/NVR प्रकार) समाविष्ट करा.",
        "YNK टीमकडून नियमित ऑडिट करा जेणेकरून मंजूर मानकांनुसार स्थापना सुनिश्चित होईल.",
      ],
      mitigation_en: [
        "Standardize CCTV brand across all outlets → Only CP Plus cameras to be used.",
        "Communicate clearly to branch owners that brand compliance is mandatory for approvals.",
        "Include CCTV specifications (resolution, storage, DVR/NVR type) in civil work checklist.",
        "Regular audits by YNK team to ensure installation as per approved standards.",
      ],
    },
    {
      id: "permissions_required",
      title_mr: "आवश्यक परवानग्या",
      title_en: "Permissions Required",
      challenges_mr: [
        "सोसायटी चेअरमन, दुकान मालक, कॉर्पोरेशन इ. कडून अनेक परवानग्या आवश्यक आहेत.",
        "काम सुरू होण्यापूर्वी परवानग्या मिळाल्या नाहीत तर विलंब होतो.",
      ],
      challenges_en: [
        "Multiple permissions required (Society Chairman, shop owner, corporation, etc.).",
        "Delays if permissions are not obtained before work starts.",
      ],
      mitigation_mr: [
        "शाखा मालकाने सिव्हिल काम सुरू होण्यापूर्वी सर्व लेखी परवानग्या मिळवाव्या.",
        "आवश्यक परवानग्या समाविष्ट करा: सोसायटी चेअरमन आणि दुकान मालक NOC, कॉर्पोरेशन मंजूरी शॉप बोर्ड साइनेजसाठी, अ‍ॅव्हनिंग शेड स्थापना मंजूरी, ड्रेनेज आउटलेट लाईन परवानगी, वॉटर टँक ठेवण्याची परवानगी (पॉटमाला), इलेक्ट्रिकल आणि प्लंबिंग कामासाठी कौन्सिल मंजूरी, भिंत/फ्लोर टायल्स बदलांसाठी परवानगी, एक्झॉस्ट फॅन किंवा डक्टिंग स्थापणेसाठी परवानगी.",
        "साइट हँडओव्हरपूर्वी परवानगी चेकलिस्टवर सही करा.",
      ],
      mitigation_en: [
        "Branch owner must secure all written permissions before commencement of civil work.",
        "Permissions required include: Society Chairman and Shop Owner NOC, Corporation approval for shop board signage, Approval for awning shed installation, Drainage outlet line permission, Water tank placement (Potmala), Electrical & plumbing work council clearance, Permission for wall/floor tile changes, Permission for exhaust fan or ducting installation.",
        "Maintain a permission checklist signed off before site handover.",
      ],
    },
    {
      id: "electrical_plumbing_safety",
      title_mr: "इलेक्ट्रिकल, प्लंबिंग आणि सुरक्षा अनुपालन",
      title_en: "Electrical, Plumbing & Safety Compliance",
      challenges_mr: [
        "कौन्सिल मंजूरीत विलंब होतो.",
        "इअर्थिंग आवश्यकता वारंवार दुर्लक्षित केली जाते.",
      ],
      challenges_en: [
        "Council clearance delays.",
        "Earthing requirements often ignored.",
      ],
      mitigation_mr: [
        "इलेक्ट्रिकल आणि प्लंबिंग काम सुरू होण्यापूर्वी कौन्सिल मंजूरी मिळवा.",
        "प्रत्येक आउटलेटवर योग्य इअर्थिंग स्थापना सुनिश्चित करा.",
        "सुरक्षा अनुपालनाची पुष्टी करण्यासाठी प्रमाणित कंत्राटदार नियुक्त करा.",
      ],
      mitigation_en: [
        "Obtain council permission before electrical and plumbing work begins.",
        "Ensure proper earthing installation at every outlet.",
        "Appoint a certified contractor to confirm safety compliance.",
      ],
    },
    {
      id: "execution_oversight",
      title_mr: "अंमलबजावणी देखरेख",
      title_en: "Execution Oversight",
      challenges_mr: [
        "शाखा मालक वैयक्तिक कामात व्यस्त असतो, त्यामुळे साइटवर देखरेख करता येत नाही.",
        "देखरेख नसताना कामगार चुका करतात.",
        "मालकाकडून स्थानिक विक्रेते कमी खर्चात काम करतात परंतु गुणवत्ता धोक्यात येते.",
      ],
      challenges_en: [
        "Branch owner often busy with personal work, unable to supervise on-site.",
        "Workers make mistakes in absence of supervision.",
        "Local vendors used by the owner may work at lower cost but compromise quality.",
      ],
      mitigation_mr: [
        "मालकाच्या बाजूने अधिकृत प्रतिनिधी सिव्हिल कामादरम्यान उपस्थित राहावा.",
        "YNK टीमकडून नियंत्रित तपासण्या करा.",
        "विक्रेत्यांना मंजूर लेआउट, टायल, POP आणि डक्टिंग मार्गदर्शक तत्त्वे शेअर करा जेणेकरून चुका टाळतील.",
        "प्लंबिंग, इलेक्ट्रिकल, डक्टिंग यांसारख्या महत्त्वाच्या कामांसाठी फक्त कुशल विक्रेत्यांचा वापर करा.",
        "पेंटिंग, स्वच्छता इ. तांत्रिक नसलेल्या कामांसाठी स्थानिक विक्रेत्यांचा वापर खर्च बचतीसाठी परवानगी आहे.",
      ],
      mitigation_en: [
        "Assign an authorized representative from the owner’s side to be present during civil work.",
        "YNK team to conduct periodic inspections.",
        "Share approved layout, tile, POP, and ducting guidelines with vendors to avoid mistakes.",
        "Strictly enforce use of skilled vendors for critical work (plumbing, electrical, ducting).",
        "Cost-saving through local vendors allowed only for non-technical tasks (painting, cleaning, etc.).",
      ],
    },
    {
      id: "general_guidelines",
      title_mr: "सर्वसाधारण मिता दिशानिर्देश",
      title_en: "General Mitigation Guidelines",
      challenges_mr: [],
      challenges_en: [],
      mitigation_mr: [
        "फ्रँचाईझी मालक आणि हितसंबंधींसोबत आवश्यकता स्पष्टपणे संवाद साधा.",
        "प्रत्येक प्रकल्पासाठी एकच संपर्क बिंदू निश्चित करा.",
        "काम सुरू होण्यापूर्वी सखोल साइट मूल्यांकन करा.",
        "आवश्यक सर्व परवानग्या आणि मंजुरी आगाऊ मिळवा.",
        "बदल किंवा अपेक्षित समस्यांचा विचार करून प्रकल्प योजना नियमितपणे पुनरावलोकन आणि अपडेट करा.",
        "समस्यांचे त्वरित निराकरण करण्यासाठी उघड संवाद मार्ग ठेवा.",
      ],
      mitigation_en: [
        "Clearly communicate requirements with franchise owners and stakeholders.",
        "Establish a single point of contact for each project.",
        "Conduct thorough site assessments before starting work.",
        "Obtain all necessary permissions and approvals in advance.",
        "Regularly review and update project plans to reflect changes or unexpected issues.",
        "Maintain open communication channels to resolve issues promptly.",
      ],
    },
  ],
  submit_button_mr: "सबमिट करा",
  submit_button_en: "Submit",
  navigation_buttons: {
    back_mr: "मागे",
    back_en: "Back",
    next_mr: "पुढे",
    next_en: "Next",
  },
  submission_message_mr:
    "धन्यवाद की आपण चॅलेंजेस प्लॅन १ साठी माहिती दिली. आम्ही 24 तासांच्या आत पुढील कार्यवाहीची माहिती देऊ.",
  submission_message_en:
    "Thank you for providing information for Challenges Plan 1. We will provide further action details within 24 hours.",
};

export default ChallangesPlan1Questions;