const ChallengesPlan1Questions = {
  id: "challenges_plan1_form",
  title_mr: "चॅलेंजेस प्लॅन १ साठी नियोजन",
  title_en: "PLANNING FOR CHALLENGES PLAN 1",
  steps: [
    {
      id: "area_shop_size",
      title_mr: "क्षेत्र (दुकान आकार आणि स्टोर रूम)",
      title_en: "Area (Shop Size & Store Room)",
      challenges_mr: [
        "दुकान आकार (150–300 चौ.फूट) सेटअप आणि ऑपरेशन्समध्ये अडचणी निर्माण करतो.",
        "कच्च्या मालाची साठवणूक अपुरी आहे.",
        "बंद केल्यानंतर गोल टेबल्स ठेवण्यात अडचण येते.",
      ],
      challenges_en: [
        "Limited shop size (150–300 sq.ft.) creates issues in setup and operations.",
        "Insufficient raw material storage.",
        "Difficulty in placing round tables after closing.",
      ],
      mitigation_mr: [
        "किमान 300 चौ.फूट क्षेत्र स्टोर रूमसह प्रदान करा.",
        "लहान दुकानांसाठी बाहेरील समर्पित साठवणूक जागा व्यवस्थापित करा किंवा कॉम्पॅक्ट साठवणूक समाधान तयार करा.",
        "फर्निचर लेआउट ऑप्टिमाइझ करा जेणेकरून बंद केल्यानंतर साठवणूक लवचिकता सुनिश्चित होईल.",
      ],
      mitigation_en: [
        "Provide minimum 300 sq.ft. area including store room.",
        "For smaller shops, arrange dedicated storage space externally or create compact storage solutions.",
        "Optimize furniture layout to ensure post-closing storage flexibility.",
      ],
    },
    {
      id: "layout",
      title_mr: "लेआउट",
      title_en: "Layout",
      challenges_mr: [
        "थीम-आधारित लेआउट तयार केलेले आहे, परंतु मालकाकडून अखेरचे बदल वारंवार केले जातात.",
        "NB FIDM टीमच्या मंजुरीत विलंब होतो.",
      ],
      challenges_en: [
        "Theme-based layout prepared but final changes often made by owner.",
        "Delays in NB FIDM team approval.",
      ],
      mitigation_mr: [
        "मालकाच्या बाजूने एक अधिकृत व्यक्ती मंजुरीसाठी नियुक्त करा.",
        "अंमलबजावणीपूर्वी NB टीमकडून सोपी आणि थेट मंजुरी मिळवा.",
        "सर्व हितसंबंधींच्या सह्या घेऊन अंतिम लेआउट लॉक करा.",
      ],
      mitigation_en: [
        "Appoint one authorized person from the owner's side for approvals.",
        "Obtain easy and direct approvals from NB team before execution.",
        "Ensure final layout is locked and signed off by all stakeholders.",
      ],
    },
    {
      id: "wall_tiles_work",
      title_mr: "वॉल टाइल्स कार्य",
      title_en: "Wall Tiles Work",
      challenges_mr: [
        "अस्तित्वातील टाइल्स नवीन थीमसह विसंगत आहेत.",
        "दुकान आकारातील बदल अंमलबजावणीस प्रभावित करतात.",
        "बजेट मर्यादा; मालक टाइल्स बदलण्यास हिचकतात.",
        "मालक टाइल्स बदलण्यास नकार देऊ शकतात.",
      ],
      challenges_en: [
        "Existing tiles conflict with new theme.",
        "Variation in shop sizes affects implementation.",
        "Budget constraints; owners hesitate to replace tiles.",
        "Owners may refuse to change tiles.",
      ],
      mitigation_mr: [
        "स्वीकारार्ह टाइल्स पर्यायांबाबत स्पष्ट खुलासा द्या.",
        "कार्पेट क्षेत्राच्या आधारावर थीम लॉक करा.",
        "पर्यायी समाधान ऑफर करा (टाइल क्लॅडिंग, पेंटिंग, आंशिक बदल).",
      ],
      mitigation_en: [
        "Provide clear clarification on acceptable tile options.",
        "Lock theme based on carpet area.",
        "Offer alternate solutions (tile cladding, painting, partial replacement).",
      ],
    },
    {
      id: "plumbing_electrical_work",
      title_mr: "प्लंबिंग आणि इलेक्ट्रिकल कार्य",
      title_en: "Plumbing & Electrical Work",
      challenges_mr: [
        "भिंतीची जाडी 6 इंचापेक्षा कमी आहे, ज्यामुळे लपलेले काम अडचणीत येते.",
        "सोसायटी, दुकान मालक आणि शेजाऱ्यांकडून परवानग्या आवश्यक आहेत.",
        "अर्थिंग आवश्यकता वारंवार दुर्लक्षित केली जाते.",
      ],
      challenges_en: [
        "Wall thickness less than 6” creates issues for concealed work.",
        "Permissions required from society, shop owner, and neighbours.",
        "Earthing requirements often overlooked.",
      ],
      mitigation_mr: [
        "खरे काम सुरू होण्यापूर्वी परवानगी पत्रे मिळवा.",
        "अस्तित्वातील अर्थिंग पुरेसे नसेल तर नवीन अर्थिंग स्थापित करा.",
        "लपलेले पाइपिंग/वायरिंग शक्य नसल्यास, नीटनेटके फिनिशिंगसह उघडे काम करा.",
      ],
      mitigation_en: [
        "Obtain permission letters before actual work starts.",
        "Install new earthing if existing is not adequate.",
        "If concealed piping/wiring not possible, execute as open work with neat finishing.",
      ],
    },
    {
      id: "electrical_plumbing_safety_compliance",
      title_mr: "इलेक्ट्रिकल, प्लंबिंग आणि सुरक्षा अनुपालन",
      title_en: "Electrical, Plumbing & Safety Compliance",
      challenges_mr: [
        "परिषदेच्या मंजुरीत विलंब होतो.",
        "अर्थिंग आवश्यकता अनेकदा दुर्लक्षित केल्या जातात.",
        "इलेक्ट्रिकल आणि प्लंबिंग कामासाठी प्रमाणित कंत्राटदाराची आवश्यकता.",
      ],
      challenges_en: [
        "Council clearance delays.",
        "Earthing requirements often ignored.",
        "Requirement for certified contractor for electrical and plumbing work.",
      ],
      mitigation_mr: [
        "इलेक्ट्रिकल आणि प्लंबिंग काम सुरू होण्यापूर्वी परिषदेची परवानगी मिळवा.",
        "प्रत्येक आउटलेटवर योग्य अर्थिंग स्थापना सुनिश्चित करा.",
        "सुरक्षा अनुपालनाची खात्री करण्यासाठी प्रमाणित कंत्राटदार नियुक्त करा.",
      ],
      mitigation_en: [
        "Obtain council permission before electrical and plumbing work begins.",
        "Ensure proper earthing installation at every outlet.",
        "Appoint a certified contractor to confirm safety compliance.",
      ],
    },
    {
      id: "pop_ceiling_work",
      title_mr: "POP (फॉल्स सीलिंग) कार्य",
      title_en: "POP (False Ceiling) Work",
      challenges_mr: [
        "विविध योजना पर्याय (पार्टिशन POP / पूर्ण POP / नाही POP).",
        "सीलिंगवर टिन शेड आहे.",
        "दुकान उंची 9 फूटपेक्षा कमी आहे.",
      ],
      challenges_en: [
        "Different plan options (partition POP / full POP / no POP).",
        "Ceiling has tin shade.",
        "Shop height less than 9 ft.",
      ],
      mitigation_mr: [
        "POP आवश्यकतांबाबत स्पष्ट खुलासा द्या.",
        "दुकान उंची ≥10 फूट असल्यास टिन शेडखाली POP स्थापित करा.",
        "दुकान उंची <9 फूट असल्यास POP अंमलात आणला जाणार नाही.",
      ],
      mitigation_en: [
        "Provide clear clarification on POP requirements.",
        "POP to be installed below tin shade if shop height ≥10 ft.",
        "If shop height <9 ft, POP will not be executed.",
      ],
    },
    {
      id: "ducting_exhaust",
      title_mr: "डक्टिंग / एक्झॉस्ट",
      title_en: "Ducting / Exhaust",
      challenges_mr: [
        "बजेट मर्यादा.",
        "एक्झॉस्ट पॉईंट स्थान समस्या.",
        "परवानगी समस्या.",
        "थीम डिझाइनसह संरेखन.",
        "दुकान उंची मर्यादा.",
        "डक्ट आकार आणि क्षमता आवश्यकता.",
      ],
      challenges_en: [
        "Budget limitations.",
        "Exhaust point location issues.",
        "Permission challenges.",
        "Alignment with theme design.",
        "Shop height constraints.",
        "Duct size and capacity requirements.",
      ],
      mitigation_mr: [
        "खर्च कमी करण्यासाठी एक्झॉस्ट फॅनवर प्राधान्य द्या डक्टिंगऐवजी.",
        "एक्झॉस्ट पॉईंट उपलब्ध नसल्यास, डक्टिंग शटरपर्यंत विस्तारित करा.",
        "अंमलबजावणीपूर्वी मालकाला अंतिम योजना कळवा.",
        "दुकान उंची <8 फूट आणि परवानगी उपलब्ध नसल्यास, पार्टिशन भिंतीवर एक्झॉस्ट फॅन स्थापित करा.",
        "किमान 15”, कमाल 18” आकाराचे एक्झॉस्ट फॅन वापरा.",
      ],
      mitigation_en: [
        "Prefer exhaust fans over ducting to reduce cost.",
        "If no exhaust points available, extend ducting up to shutter.",
        "Inform owner of final plan before execution.",
        "If shop height <8 ft and permission not available, install exhaust fan on partition wall.",
        "Use exhaust fans with minimum size 15”, maximum 18”.",
      ],
    },
    {
      id: "board_signage_work",
      title_mr: "बोर्ड / साइनेज कार्य",
      title_en: "Board / Signage Work",
      challenges_mr: [
        "अनेक परवानग्या आवश्यक (मालक, सोसायटी, महानगरपालिका, शेजारी).",
        "बोर्ड उंची आणि लांबीवर मर्यादा.",
        "अंमलबजावणी थीमसह जुळत नाही.",
      ],
      challenges_en: [
        "Multiple permissions required (owner, society, corporation, neighbours).",
        "Restrictions on board height and length.",
        "Execution may not align with theme.",
      ],
      mitigation_mr: [
        "फ्रँचाइझी मालकाने काम सुरू होण्यापूर्वी सर्व परवानग्या मिळवाव्यात.",
        "आकार मर्यादा असल्यास, 2–3 पर्यायी साइनेज डिझाइन्स तयार करा.",
        "थीम अंमलबजावणी समस्या उद्भवल्यास, अधिकृत डिझाइन/मंजुरी प्राधिकरणाकडे वरिष्ठ करा.",
      ],
      mitigation_en: [
        "Franchise owner to secure all permissions before work begins.",
        "If size restrictions exist, prepare 2–3 alternate signage designs.",
        "In case of theme execution issues, escalate to authorized design/approval authority.",
      ],
    },
    {
      id: "gas_pipeline_work",
      title_mr: "गॅस पाइपलाइन कार्य",
      title_en: "Gas Pipeline Work",
      challenges_mr: [
        "पार्टिशन कामानंतर लांब पाइपलाइन मार्गांमुळे गॅस दाब कमी होतो.",
        "दुकानातील अनेक खांब → अतिरिक्त वाकणे (एल्बोज) आवश्यक, ज्यामुळे दाब आणखी कमी होतो.",
        "मर्यादित दुकान क्षेत्र → गॅस बँक / गॅस बुक ठेवण्यासाठी पुरेसे स्थान नाही.",
        "गॅस गळतीचा धोका → चुकीची स्थापना किंवा साहित्य मॅचिंग.",
        "साहित्य उपलब्धता समस्या → MS / GI पाइप साइटवर उपलब्ध नाही; मालक कॉपर पाइप वापरतो.",
      ],
      challenges_en: [
        "Low Gas Pressure after partition work due to longer pipeline routes.",
        "Multiple Columns in shop → requires additional bends (Elbows), causing further pressure drop.",
        "Limited shop area → insufficient space for proper gas bank / gas book placement.",
        "Gas Leakage Risks → improper installation or material mismatch.",
        "Material Availability Issues → MS / GI pipe not available on site; owner uses copper pipes instead.",
      ],
      mitigation_mr: [
        "1. गॅस दाब व्यवस्थापन",
        "• पार्टिशन कामानंतर दाब चाचणी करा.",
        "• किमान वाकणे/एल्बोज वापरा; पाइपलाइन लांबी कमी करण्यासाठी लेआउट ऑप्टिमाइझ करा.",
        "• जिथे दाब कमी होण्याची शक्यता आहे तिथे मोठ्या व्यासाचे पाइप वापरा.",
        "2. खांब अडथळे",
        "• लेआउट अंतिम करताना पाइपलाइन मार्ग नियोजित करा.",
        "• गळती/दाब कमी होण्यापासून टाळण्यासाठी उच्च दर्जाचे एल्बोज आणि फिटिंग्स वापरा.",
        "3. गॅस बँक / गॅस बुकसाठी जागेची मर्यादा",
        "• पर्यायी सुरक्षित ठिकाणे ओळखा (मागील सेटबॅक, छत, किंवा मंजूर मर्यादेत बाहेरील स्टोर).",
        "• लहान जागेसाठी डिझाइन केलेले कॉम्पॅक्ट गॅस मॅनिफोल्ड सिस्टम वापरा.",
        "4. गळती प्रतिबंध",
        "• कमिशनिंगपूर्वी सक्तीने दाब चाचणी करा.",
        "• सर्व जोडण्या मंजूर साहित्यासह सील करा.",
        "• पाइपलाइन्ससाठी नियमित देखभाल आणि तपासणी वेळापत्रक.",
        "5. साहित्य मानकीकरण",
        "• सुरक्षा मानकांनुसार फक्त मंजूर साहित्य (MS/GI पाइप) वापरा.",
        "• तात्पुरती जोडणीसाठी फक्त कॉपर पाइपिंग परवानगी आहे आणि त्याने ISI सुरक्षा नियमांचे पालन करावे.",
        "• शाखा मालकाने सर्टिफाइड व्हेंडरद्वारे गॅस लाइन काम सुनिश्चित करावे.",
      ],
      mitigation_en: [
        "1. Gas Pressure Management",
        "• Conduct pressure testing after partition work.",
        "• Use minimum bends/elbows; optimize layout to reduce pipeline length.",
        "• Use larger diameter pipes where pressure drop is expected.",
        "2. Column Obstructions",
        "• Plan pipeline route during layout finalization.",
        "• Use high-quality elbows and fittings to minimize leakage/pressure loss.",
        "3. Space Constraints for Gas Bank / Gas Book",
        "• Identify alternate safe locations (rear setback, rooftop, or outside store within approved limits).",
        "• Use compact gas manifold systems designed for smaller spaces.",
        "4. Leakage Prevention",
        "• Mandatory pressure test before commissioning.",
        "• Ensure all joints are sealed with approved material.",
        "• Regular maintenance & inspection schedule for pipelines.",
        "5. Material Standardization",
        "• Use only approved material (MS/GI pipes) as per safety standards.",
        "• Copper piping permitted only for temporary connections and must follow ISI safety norms.",
        "• Branch owner to ensure certified vendor executes gas line work.",
      ],
    },
    {
      id: "cctv_camera_work",
      title_mr: "सीसीटीव्ही कॅमेरा कार्य",
      title_en: "CCTV Camera Work",
      challenges_mr: [
        "शाखा मालक अनेकदा खर्च कमी करण्यासाठी कमी दर्जाचे कॅमेरे बसवतात.",
        "बिना-ब्रँडेड कॅमेरे व्हिडिओ स्पष्टता, स्टोरेज आणि सुरक्षा मानकांवर तडजोड करतात.",
        "कमी किमतीच्या सिस्टम्सची कार्यकाळ कमी असतो आणि देखभालीची समस्या जास्त असते.",
      ],
      challenges_en: [
        "Branch owners often install low-quality cameras to reduce cost.",
        "Non-branded cameras compromise on video clarity, storage, and security compliance.",
        "Low-cost systems have shorter lifespan and higher maintenance issues.",
      ],
      mitigation_mr: [
        "सर्व आउटलेटमध्ये सीसीटीव्ही ब्रँडचे मानकीकरण करा → फक्त CP Plus कॅमेरे वापरावेत.",
        "शाखा मालकांना स्पष्टपणे कळवा की मंजुरीसाठी ब्रँडचे पालन करणे बंधनकारक आहे.",
        "सिव्हिल वर्क चेकलिस्टमध्ये सीसीटीव्हीची वैशिष्ट्ये (रिझोल्यूशन, स्टोरेज, डीव्हीआर/एनव्हीआर प्रकार) समाविष्ट करा.",
        "मान्य मानकांनुसार स्थापना सुनिश्चित करण्यासाठी YNK टीमद्वारे नियमित तपासणी (ऑडिट) केली जाईल.",
      ],
      mitigation_en: [
        "Standardize CCTV brand across all outlets → Only CP Plus cameras to be used.",
        "Communicate clearly to branch owners that brand compliance is mandatory for approvals.",
        "Include CCTV specifications (resolution, storage, DVR/NVR type) in civil work checklist.",
        "Regular audits by YNK team to ensure installation as per approved standards.",
      ],
    },
    {
      id: "permissions_and_oversight",
      title_mr: "परवानग्या आणि अंमलबजावणी निरीक्षण",
      title_en: "Permissions & Execution Oversight",
      challenges_mr: [
        "अनेक परवानग्या आवश्यक आहेत (सोसायटीचे अध्यक्ष, दुकान मालक, महानगरपालिका, इत्यादी).",
        "काम सुरू होण्यापूर्वी परवानग्या मिळाल्या नाहीत तर विलंब होतो.",
      ],
      challenges_en: [
        "Multiple permissions required (Society Chairman, shop owner, corporation, etc.).",
        "Delays if permissions are not obtained before work starts.",
      ],
      mitigation_mr: [
        "शाखा मालकाने प्रत्यक्ष काम सुरू करण्यापूर्वी सर्व लिखित परवानग्या मिळवाव्यात.",
        "आवश्यक परवानग्यांमध्ये हे समाविष्ट आहे:",
        "o सोसायटीचे अध्यक्ष आणि दुकान मालकाकडून ना हरकत प्रमाणपत्र (NOC).",
        "o दुकानाच्या बोर्ड साइनेजसाठी महानगरपालिकेची मंजुरी.",
        "o अव्हनिंग शेड बसवण्यासाठी मंजुरी.",
        "o ड्रेनेज आउटलेट लाइनची परवानगी.",
        "o पाण्याची टाकी ठेवण्याचे स्थान (पोटमाळा).",
        "o इलेक्ट्रिकल आणि प्लंबिंग कामासाठी परिषदेची परवानगी.",
        "o भिंती/फ्लोअर टाइल्स बदलण्यासाठी परवानगी.",
        "o एक्झॉस्ट फॅन किंवा डक्टिंग बसवण्यासाठी परवानगी.",
        "साइट सोपवण्यापूर्वी मंजूर केलेल्या परवानगी चेकलिस्टची एक प्रत ठेवा.",
      ],
      mitigation_en: [
        "Branch owner must secure all written permissions before commencement of civil work.",
        "Permissions required include:",
        "o Society Chairman and Shop Owner NOC.",
        "o Corporation approval for shop board signage.",
        "o Approval for awning shed installation.",
        "o Drainage outlet line permission.",
        "o Water tank placement (Potmala).",
        "o Electrical & plumbing work council clearance.",
        "o Permission for wall/floor tile changes.",
        "o Permission for exhaust fan or ducting installation.",
        "Maintain a permission checklist signed off before site handover.",
      ],
    },
    {
      id: "electrical_plumbing_safety_compliance_2",
      title_mr: "2. इलेक्ट्रिकल, प्लंबिंग आणि सुरक्षा अनुपालन",
      title_en: "2. Electrical, Plumbing & Safety Compliance",
      challenges_mr: [
        "परिषदेच्या मंजुरीत विलंब होतो.",
        "अर्थिंग आवश्यकता अनेकदा दुर्लक्षित केल्या जातात.",
      ],
      challenges_en: [
        "Council clearance delays.",
        "Earthing requirements often ignored.",
      ],
      mitigation_mr: [
        "इलेक्ट्रिकल आणि प्लंबिंग काम सुरू होण्यापूर्वी परिषदेची परवानगी मिळवा.",
        "प्रत्येक आउटलेटवर योग्य अर्थिंग स्थापना सुनिश्चित करा.",
        "सुरक्षा अनुपालनाची खात्री करण्यासाठी प्रमाणित कंत्राटदार नियुक्त करा.",
      ],
      mitigation_en: [
        "Obtain council permission before electrical and plumbing work begins.",
        "Ensure proper earthing installation at every outlet.",
        "Appoint a certified contractor to confirm safety compliance.",
      ],
    },
    {
      id: "execution_oversight",
      title_mr: "3. अंमलबजावणी निरीक्षण",
      title_en: "3. Execution Oversight",
      challenges_mr: [
        "शाखा मालक वैयक्तिक कामात व्यस्त असल्याने साइटवर देखरेख करू शकत नाही.",
        "देखरेखीच्या अभावात कामगार चुका करतात.",
        "मालकाकडून वापरलेले स्थानिक विक्रेते कमी खर्चात काम करू शकतात परंतु गुणवत्तेसाठी तडजोड करतात.",
      ],
      challenges_en: [
        "Branch owner often busy with personal work, unable to supervise on-site.",
        "Workers make mistakes in absence of supervision.",
        "Local vendors used by the owner may work at lower cost but compromise quality.",
      ],
      mitigation_mr: [
        "मालकाच्या बाजूने अधिकृत प्रतिनिधी नियुक्त करा जो सिव्हिल कामादरम्यान उपस्थित असेल.",
        "YNK टीमने नियतकालिक तपासणी केली पाहिजे.",
        "चुका टाळण्यासाठी मंजूर लेआउट, टाइल, POP आणि डक्टिंग मार्गदर्शक तत्त्वे विक्रेत्यांसोबत शेअर करा.",
        "गंभीर कामासाठी (प्लंबिंग, इलेक्ट्रिकल, डक्टिंग) कुशल विक्रेत्यांचा वापर कडकपणे लागू करा.",
        "स्थानिक विक्रेत्यांद्वारे खर्च वाचवणे केवळ नॉन-तांत्रिक कामांसाठी (पेंटिंग, सफाई इ.) परवानगी आहे.",
        "सामान्य मिटिगेशन मार्गदर्शक तत्त्वे:",
        "1. फ्रँचाइझी मालक आणि हितधारकांसोबत आवश्यकता स्पष्टपणे संप्रेषण करा.",
        "2. प्रत्येक प्रकल्पासाठी एकच संपर्क बिंदू स्थापित करा.",
        "3. काम सुरू करण्यापूर्वी सखोल साइट आकलन करा.",
        "4. सर्व आवश्यक परवानग्या आणि मंजुर्या आधीच मिळवा.",
        "5. बदल किंवा अनपेक्षित समस्यांना प्रतिबिंबित करण्यासाठी प्रकल्प योजनांची नियमित पुनरावृत्ती करा.",
        "6. समस्या त्वरित सोडवण्यासाठी खुले संप्रेषण चॅनेल राखा.",
      ],
      mitigation_en: [
        "Assign an authorized representative from the owner's side to be present during civil work.",
        "YNK team to conduct periodic inspections.",
        "Share approved layout, tile, POP, and ducting guidelines with vendors to avoid mistakes.",
        "Strictly enforce use of skilled vendors for critical work (plumbing, electrical, ducting).",
        "Cost-saving through local vendors allowed only for non-technical tasks (painting, cleaning, etc.).",
        "General Mitigation Guidelines:",
        "1. Clearly communicate requirements with franchise owners and stakeholders.",
        "2. Establish a single point of contact for each project.",
        "3. Conduct thorough site assessments before starting work.",
        "4. Obtain all necessary permissions and approvals in advance.",
        "5. Regularly review and update project plans to reflect changes or unexpected issues.",
        "6. Maintain open communication channels to resolve issues promptly.",
      ],
    },
  ],
  submit_button_mr: "सबमिट करा",
  submit_button_en: "Submit",
  navigation_buttons: {
    back_mr: "मागे",
    back_en: "Back",
    next_mr: "पुढे",
    next_en: "Next",
  },
  submission_message_mr:
    "धन्यवाद की आपण चॅलेंजेस प्लॅन १ साठी माहिती दिली. आम्ही 24 तासांच्या आत पुढील कार्यवाहीची माहिती देऊ.",
  submission_message_en:
    "Thank you for providing information for Challenges Plan 1. We will provide further action details within 24 hours.",
};

export default ChallengesPlan1Questions;