const call4Questions = [
  {
    id: 1,
    mr: "नमस्कार सर, मी YNK ग्रुपमधून बोलत आहे, फीडबॅकसाठी कॉल आहे. तुमच्याकडे 2 मिनिटे वेळ आहे का?",
    en: "Hello sir, I am calling from YNK Group. This is a feedback call. Do you have 2 minutes?",
    type: "yesno",
  },
  {
    id: 2,
    mr: "सर, आपल्याला सर्व वस्तू कशा चालू करायच्या याबद्दल माहिती आहे का?",
    en: "Sir, do you know how to operate all the items?",
    type: "yesno",
  },
  {
    id: 3,
    mr: "सर, आपण इडली स्टीमरबद्दल ट्रेनिंग घेतलेली आहे का?",
    en: "Sir, have you received training for the idli steamer?",
    type: "yesno",
  },
  {
    id: 4,
    mr: "सर, इडली स्टीमर बॉयलरमध्ये पाणी कशा प्रकारे आपण सोडू शकतो, याची ट्रेनिंग आपण घेतलेली आहे का?",
    en: "Sir, have you been trained on how to fill water into the idli steamer boiler?",
    type: "yesno",
  },
  {
    id: 5,
    mr: "सर, इडली स्टीमरची कॅपॅसिटी किती आहे, याची ट्रेनिंग आपण घेतली आहे का?",
    en: "Sir, have you been trained on the capacity of the idli steamer?",
    type: "yesno",
  },
  {
    id: 6,
    mr: "सर, इडली स्टीमर लेव्हल ट्यूबबद्दल माहिती आपण घेतली आहे का?",
    en: "Sir, have you received information about the idli steamer's level tube?",
    type: "yesno",
  },
  {
    id: 7,
    mr: "सर, इडली स्टीमर लेव्हल ट्यूब काम करत नाही, तर स्टीमर कसे काम करतो याची माहिती आपण घेतली आहे का?",
    en: "Sir, have you received information on how the steamer works if the level tube is not functioning?",
    type: "yesno",
  },
  {
    id: 8,
    mr: "सर, आपल्याला इडली स्टीमर हाताळताना काही प्रॉब्लेम येत आहेत का?",
    en: "Sir, are you facing any problems while handling the idli steamer?",
    type: "yesno",
  },
  {
    id: 9,
    mr: "सर, आपण मिक्सरबद्दल ट्रेनिंग घेतली आहे का?",
    en: "Sir, have you received training for the mixer?",
    type: "yesno",
  },
  {
    id: 10,
    mr: "सर, मिक्सरची स्पीड, कॅपॅसिटी आणि मटेरियल किती प्रमाणामध्ये वापरायचे, याबद्दल तुम्हाला माहिती दिली आहे का?",
    en: "Sir, were you informed about the mixer's speed, capacity, and the quantity of material to use?",
    type: "yesno",
  },
  {
    id: 11,
    mr: "सर, आपण शॉपमधील कुकर कशा प्रकारे वापरायचा, याची पूर्ण ट्रेनिंग घेतलेली आहे का?",
    en: "Sir, have you received complete training on how to use the cooker in the shop?",
    type: "yesno",
  },
  {
    id: 12,
    mr: "सर, आपण थर्मास, वजन काटा, मेन्यू फ्रेम, राऊंड टेबल, यांची पूर्ण माहिती करून घेतली आहे का?",
    en: "Sir, have you received complete information about the thermos, weighing scale, menu frame, and round table?",
    type: "yesno",
  },
  {
    id: 13,
    mr: "सर, फ्रीजबद्दल आपण ट्रेनिंग घेतलेली आहे का?",
    en: "Sir, have you received training for the fridge?",
    type: "yesno",
  },
  {
    id: 14,
    mr: "सर, आपल्याला फ्रीजची कॅपॅसिटी किती आहे आणि स्पीड किती ठेवायचा, याबद्दल पूर्ण माहिती आपण घेतली आहे का?",
    en: "Sir, have you received complete information about the fridge's capacity and what speed to set it at?",
    type: "yesno",
  },
  {
    id: 15,
    mr: "सर, आपण कॉफी मशीन कशी वापरायची याची ट्रेनिंग घेतलेली आहे का?",
    en: "Sir, have you received training on how to use the coffee machine?",
    type: "yesno",
  },
  {
    id: 16,
    mr: "सर, सर्व्हिस काउंटरला कॉईल आहे, याचा वापर कसा करायचा याची ट्रेनिंग आपण घेतलेली आहे का?",
    en: "Sir, have you been trained on how to use the coil in the service counter?",
    type: "yesno",
  },
  {
    id: 17,
    mr: "सर, शॉपमधील साऊंड सिस्टीम कशासाठी आहे, याची माहिती आपण घेतलेली आहे का?",
    en: "Sir, have you been trained on the purpose of the sound system in the shop?",
    type: "yesno",
  },
  {
    id: 18,
    mr: "सर, आपण शॉपमधील बिल मशीनबद्दल पूर्ण ट्रेनिंग घेतली आहे का?",
    en: "Sir, have you received complete training for the billing machine in the shop?",
    type: "yesno",
  },
  {
    id: 19,
    mr: "सर, आपण बिल मशीन सॉफ्टवेअरबद्दल पूर्ण माहिती घेतली आहे का?",
    en: "Sir, have you received complete information about the billing machine software?",
    type: "yesno",
  },
  {
    id: 20,
    mr: "सर, शॉपमधील गॅस पाइपिंगबद्दल आपण ट्रेनिंग घेतलेली आहे का?",
    en: "Sir, have you received training regarding the gas piping in the shop?",
    type: "yesno",
  },
  {
    id: 21,
    mr: "सर, आपण शॉपमध्ये फायर टँक कसा ओपन करायचा, याची ट्रेनिंग आपण घेतली आहे का?",
    en: "Sir, have you been trained on how to operate the fire tank in the shop?",
    type: "yesno",
  },
  {
    id: 22,
    mr: "सर, शॉपमधील CCTV कॅमेऱ्याबद्दल, याची ट्रेनिंग आपण घेतली आहे का?",
    en: "Sir, have you received training regarding the CCTV camera in the shop?",
    type: "yesno",
  },
  {
    id: 23,
    mr: "सर, शॉपमधील साईड टेबल तसेच पाण्याचे सिंक कसे वापरायचे, याबद्दल माहिती आपण घेतली आहे का?",
    en: "Sir, have you received information on how to use the side table and the water sink in the shop?",
    type: "yesno",
  },
  {
    id: 24,
    mr: "सर, आपल्याला YNK कंपनीकडून इंजिनिअर किंवा मॅनेजर यांच्याकडून वस्तू वापरण्याची पूर्ण माहिती दिली आहे का?",
    en: "Sir, have you been given complete information on using the items by an engineer or manager from YNK Company?",
    type: "yesno",
  },
  {
    id: 25,
    mr: "आपल्याला कोणत्या वस्तूबद्दल माहिती YNK कंपनीकडून मिळालेली नाही?",
    en: "About which item have you not received information from YNK Company?",
    type: "text",
  },
  {
    id: 26,
    mr: "सर, तुम्ही इंजिनिअर यांना 1 ते 5 पैकी किती रेटिंग देणार?",
    en: "Sir, what rating would you give the engineer, out of 1 to 5?",
    type: "rating",
  },
];

export default call4Questions;