const call4Questions = [
  {
    id: 1,
    mr: "नमस्कार सर, मी YNK ग्रुपमधून बोलत आहे. फीडबॅकसाठी कॉल आहे, तुमच्याकडे २ मिनिटे वेळ आहे का?",
    en: "Hello Sir, I'm calling from YNK Group. This is a feedback call, do you have 2 minutes?",
    type: "yesno",
  },
  {
    id: 2,
    mr: "सर, तुम्हाला सर्व वस्तू कशा चालवायच्या याबद्दल माहिती आहे का?",
    en: "Sir, do you have the information on how to operate all the items?",
    type: "yesno",
  },
  {
    id: 3,
    mr: "सर, तुम्ही इडली स्टीमरबद्दल ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training for the idli steamer?",
    type: "yesno",
  },
  {
    id: 4,
    mr: "सर, इडली स्टीमरच्या बॉयलरमध्ये पाणी कसे भरावे, याचे ट्रेनिंग तुम्ही घेतले आहे का?",
    en: "Sir, have you been trained on how to fill water in the idli steamer's boiler?",
    type: "yesno",
  },
  {
    id: 5,
    mr: "सर, इडली स्टीमरची क्षमता किती आहे, याचे ट्रेनिंग तुम्ही घेतले आहे का?",
    en: "Sir, have you received training regarding the capacity of the idli steamer?",
    type: "yesno",
  },
  {
    id: 6,
    mr: "सर, इडली स्टीमरच्या लेव्हल ट्यूबबद्दल तुम्ही माहिती घेतली आहे का?",
    en: "Sir, have you received information about the idli steamer's level tube?",
    type: "yesno",
  },
  {
    id: 7,
    mr: "सर, इडली स्टीमरची लेव्हल ट्यूब काम करत नसल्यास, स्टीमर कसा वापरावा याची माहिती तुम्ही घेतली आहे का?",
    en: "Sir, have you received information on how to operate the steamer if its level tube is not working?",
    type: "yesno",
  },
  {
    id: 8,
    mr: "सर, तुम्हाला इडली स्टीमर हाताळताना काही समस्या येत आहेत का?",
    en: "Sir, are you facing any problems while handling the idli steamer?",
    type: "yesno",
  },
  {
    id: 9,
    mr: "सर, तुम्ही मिक्सरबद्दल ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training for the mixer?",
    type: "yesno",
  },
  {
    id: 10,
    mr: "सर, मिक्सरचा वेग, क्षमता आणि त्यात किती प्रमाणात साहित्य वापरावे, याबद्दल तुम्हाला माहिती दिली आहे का?",
    en: "Sir, have you been informed about the mixer's speed, capacity, and the quantity of ingredients to use?",
    type: "yesno",
  },
  {
    id: 11,
    mr: "सर, तुम्ही शॉपमधील कुकर कसा वापरायचा याचे पूर्ण ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received complete training on how to use the cooker in the shop?",
    type: "yesno",
  },
  {
    id: 12,
    mr: "सर, तुम्ही थर्मास, वजन काटा, मेन्यू फ्रेम आणि राऊंड टेबल यांची पूर्ण माहिती घेतली आहे का?",
    en: "Sir, have you received complete information about the thermos, weighing scale, menu frame, and round table?",
    type: "yesno",
  },
  {
    id: 13,
    mr: "सर, तुम्ही फ्रीजबद्दल ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training for the fridge?",
    type: "yesno",
  },
  {
    id: 14,
    mr: "सर, फ्रीजची क्षमता किती आहे आणि त्याचा वेग किती ठेवावा, याबद्दल तुम्ही पूर्ण माहिती घेतली आहे का?",
    en: "Sir, have you received complete information about the fridge's capacity and what speed to set it at?",
    type: "yesno",
  },
  {
    id: 15,
    mr: "सर, तुम्ही कॉफी मशीन कशी वापरायची याचे ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training on how to use the coffee machine?",
    type: "yesno",
  },
  {
    id: 16,
    mr: "सर, सर्व्हिस काउंटरला जी कॉइल आहे, तिचा वापर कसा करायचा याचे ट्रेनिंग तुम्ही घेतले आहे का?",
    en: "Sir, have you been trained on how to use the coil in the service counter?",
    type: "yesno",
  },
  {
    id: 17,
    mr: "सर, शॉपमधील साऊंड सिस्टीम कशासाठी आहे, याची माहिती तुम्ही घेतली आहे का?",
    en: "Sir, have you received information about the purpose of the sound system in the shop?",
    type: "yesno",
  },
  {
    id: 18,
    mr: "सर, तुम्ही शॉपमधील बिल मशीनबद्दल पूर्ण ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received complete training for the billing machine in the shop?",
    type: "yesno",
  },
  {
    id: 19,
    mr: "सर, तुम्ही बिल मशीनच्या सॉफ्टवेअरबद्दल पूर्ण माहिती घेतली आहे का?",
    en: "Sir, have you received complete information about the billing machine's software?",
    type: "yesno",
  },
  {
    id: 20,
    mr: "सर, तुम्ही शॉपमधील गॅस पाइपिंगबद्दल ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training regarding the gas piping in the shop?",
    type: "yesno",
  },
  {
    id: 21,
    mr: "सर, तुम्ही शॉपमधील फायर एक्स्टिंग्विशर (Fire Extinguisher) कसा वापरायचा याचे ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you been trained on how to use the fire extinguisher in the shop?",
    type: "yesno",
  },
  {
    id: 22,
    mr: "सर, तुम्ही शॉपमधील CCTV कॅमेऱ्यांबद्दल ट्रेनिंग घेतले आहे का?",
    en: "Sir, have you received training regarding the CCTV cameras in the shop?",
    type: "yesno",
  },
  {
    id: 23,
    mr: "सर, शॉपमधील साइट टेबल आणि पाण्याचा सिंक कसा वापरायचा, याबद्दल तुम्ही माहिती घेतली आहे का?",
    en: "Sir, have you received information on how to use the side tables and the water sink in the shop?",
    type: "yesno",
  },
  {
    id: 24,
    mr: "सर, तुम्हाला YNK कंपनीकडून इंजिनिअर किंवा मॅनेजरने वस्तू वापरण्याबद्दल पूर्ण माहिती दिली आहे का?",
    en: "Sir, have you been given complete information by an engineer or a manager from YNK Company on how to use the items?",
    type: "yesno",
  },
  {
    id: 25,
    mr: "तुम्हाला कोणत्या वस्तूविषयी YNK कंपनीकडून माहिती मिळालेली नाही?",
    en: "About which item have you not received information from YNK Company?",
    type: "text",
  },
  {
    id: 26,
    mr: "सर, तुम्ही इंजिनिअरला 1 ते ५ पैकी किती रेटिंग द्याल?",
    en: "Sir, what rating would you give the engineer: 3, 4, or 5?",
    type: "rating",
  },
];

export default call4Questions;