const call1Questions = [
  {
    id: 1,
    mr: "नमस्कार सर, मी YNK ग्रुपमधून बोलत आहे. फीडबॅकसाठी कॉल केला आहे, तुमच्याकडे २ मिनिटे वेळ आहे का?",
    en: "Hello Sir, I’m calling from YNK Group for feedback. Do you have 2 minutes?",
    type: "yesno",
  },
  {
    id: 2,
    mr: "सर, आपण 'नादब्रम्ह' हा जो प्रोजेक्ट घेतला आहे, त्याबद्दल तुम्हाला पूर्ण माहिती मिळाली का?",
    en: "Sir, did you receive complete information about the 'Nadbrahma' project you undertook?",
    type: "yesno",
  },
  {
    id: 3,
    mr: "सर, आपल्याला YNK ऑफिसपर्यंत पोहोचायला काही त्रास झाला का?",
    en: "Did you face any difficulties reaching the YNK office?",
    type: "yesno",
  },
  {
    id: 4,
    mr: "सर, आपल्याला आमच्या इंजिनिअरने सर्वेक्षण करताना व्यवस्थित माहिती दिली का?",
    en: "Did our engineer provide you with proper information during the survey?",
    type: "yesno",
  },
  {
    id: 5,
    mr: "सर, आमच्या ऑफिसमध्ये तुम्हाला रिसेप्शनिस्टने चहा, कॉफी किंवा नाश्ता विचारला का?",
    en: "Did the receptionist offer you tea, coffee, or snacks at our office?",
    type: "yesno",
  },
  {
    id: 6,
    mr: "सर, आपल्याला ऑफिसमध्ये कोणाला भेटायचे आहे, याबद्दल रिसेप्शनिस्टने विचारले का?",
    en: "Did the receptionist ask whom you wanted to meet at the office?",
    type: "yesno",
  },
  {
    id: 7,
    mr: "सर, आपल्याला आमच्या ऑफिसमध्ये खूप वेळ थांबावे लागले का?",
    en: "Did you have to wait for a long time at our office?",
    type: "yesno",
  },
  {
    id: 8,
    mr: "सर, आपण ज्यांना भेटायला आला होतात, त्यांनी वेळेवर आपल्यासोबत मीटिंग घेतली का?",
    en: "Did the person you came to meet conduct the meeting on time?",
    type: "yesno",
  },
  {
    id: 9,
    mr: "सर, आपल्याला आमच्या कंपनीच्या मॅनेजरने नमस्कार केला का?",
    en: "Did the company manager greet you properly?",
    type: "yesno",
  },
  {
    id: 10,
    mr: "सर, आपल्याला आमच्या कंपनीच्या मॅनेजरने चहा किंवा नाश्त्याबद्दल विचारले का?",
    en: "Did the manager offer you tea or snacks?",
    type: "yesno",
  },
  {
    id: 11,
    mr: "सर, आपल्याला YNK मॅनेजरने प्रोजेक्ट प्रेझेंटेशन दाखवले का?",
    en: "Did the YNK manager show you the project presentation?",
    type: "yesno",
  },
  {
    id: 12,
    mr: "सर, आपल्याला 'नादब्रम्ह' प्रोजेक्टचे प्रेझेंटेशन पूर्णपणे समजले का?",
    en: "Did you fully understand the 'Nadbrahma' project presentation?",
    type: "yesno",
  },
  {
    id: 13,
    mr: "सर, आपल्याला ॲग्रीमेंटबद्दल मॅनेजरने पूर्ण माहिती दिली का?",
    en: "Did the manager explain the agreement to you thoroughly?",
    type: "yesno",
  },
  {
    id: 14,
    mr: "सर, आपल्याला शॉपमधील सर्व वस्तूंबद्दल मॅनेजरने माहिती दिली का?",
    en: "Did the manager explain all the items in the shop to you?",
    type: "yesno",
  },
  {
    id: 15,
    mr: "सर, आपण घेतलेल्या शॉपमधील सर्व कामांचा 2D प्लॅन सिव्हिल टीमने दिला का?",
    en: "Did the civil team provide the 2D plan for all the work in the shop you have taken?",
    type: "yesno",
  },
  {
    id: 16,
    mr: "सर, मॅनेजरने आपल्याला काही चुकीची माहिती दिली असे तुम्हाला वाटले का?",
    en: "Do you feel the manager provided any incorrect information?",
    type: "yesno",
  },
  {
    id: 17,
    mr: "सर, आपल्याला आमच्या ऑफिसमध्ये काही त्रास झाला का?",
    en: "Did you face any trouble at our office?",
    type: "yesno",
  },
  {
    id: 18,
    mr: "सर, आपल्याला कोणाकडून कमिशन किंवा पेमेंटची मागणी झाली का?",
    en: "Was a demand for commission or payment made to you by anyone?",
    type: "yesno",
  },
  {
    id: 19,
    mr: "सर, आपल्याला ऑफिसमधील कोणाबद्दल काही तक्रार करायची आहे का?",
    en: "Do you have a complaint regarding anyone in the office?",
    type: "yesno",
  },
  {
    id: 20,
    mr: "सर, माझे सर्व प्रश्न तुम्हाला व्यवस्थित समजले का?",
    en: "Did you understand all my questions correctly?",
    type: "yesno",
  },
  {
    id: 21,
    mr: "सर, तुमचा बहुमूल्य वेळ आम्हाला दिल्याबद्दल आम्ही तुमचे आभारी आहोत.",
    en: "Sir, thank you for giving us your valuable time.",
    type: "info",
  },
  {
    id: 22,
    mr: "सर, तुम्ही मॅनेजरला १ ते ५ पैकी किती रेटिंग द्याल?",
    en: "How would you rate the manager on a scale of 1 to 5?",
    type: "rating",
  },
];

export default call1Questions;